#!/bin/bash  
##Dependent on software installation
rpm -q gcc || yum -y install gcc
##Unzip Redis package
tar -zxvf redis-4.0.8.tar.gz
cd redis-4.0.8
##Compile and install
make && make install
##Initialization configuration
./utils/install_server.sh
##Change IP and port of main configuration file
sed -i '70s/.*/bind 192.168.4.'$1'/' /etc/redis/6379.conf
sed -i '93s/.*/port 63'$1'/' /etc/redis/6379.conf
